
SUBDIRS =  gpio int lcd lcd_ACX502BMU leds mmu nand sdram uart

all: subdirs

subdirs:
	for n in $(SUBDIRS); do $(MAKE) -C $$n || exit 1; done

clean:
	for n in $(SUBDIRS); do $(MAKE) -C $$n clean; done
